[package]
name = "zk-circuits"
version = "1.0.0"
edition = "2021"
description = "Halo2 zero-knowledge proof circuits for community P2P lending"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
halo2_proofs = "0.3"
halo2_gadgets = "0.3"
pasta_curves = "0.5"
ff = "0.13"
group = "0.13"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# For Node.js FFI bindings
napi = { version = "2.13", features = ["napi4"] }
napi-derive = "2.13"
libc = "0.2"

[dev-dependencies]
criterion = "0.4"